'use client';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { AlertDialogCancel } from './ui/alert-dialog';
import { Button } from './ui/button';
import { TableBody, TableRow } from './ui/table';
import { Input } from './ui/input';
import { SelectContent, SelectItem } from './ui/select';
import { Card } from './ui/card';

export const MotionDiv = motion.div;
export const MotionAside = motion.aside;
export const MotionNav = motion.nav;
export const MotionLink = motion.create(Link);
export const MotionSVG = motion.svg;
export const MotionSpan = motion.span;
export const MotionHeader = motion.header;
export const MotionForm = motion.form;
export const MotionButton = motion.create(Button);
export const MotionAlertDialogCancel = motion.create(AlertDialogCancel);
export const MotionTableRow = motion.create(TableRow);
export const MotionTableBody = motion.create(TableBody);
export const MotionInput = motion.create(Input);
export const MotionSelectContent = motion.create(SelectContent);
export const MotionSelectItem = motion.create(SelectItem);
export const MotionH3 = motion.h3;
export const MotionH2 = motion.h2;
export const MotionCard = motion.create(Card);
export const MotionLi = motion.li;
export const MotionP = motion.p;
